version: "3.4"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw # Optional: to specify the database name
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - "./mongodb_data_container:/data/db"
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  animal-service:
    build:
      context: .
      dockerfile: Services/AnimalService/Dockerfile
    ports:
      - "7001:8080"
      - "6001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Postgres__ConnectionString=Host=postgres;Port=5432;Username=postgres;Password=postgrespw;Database=AnimalServiceDb
      - RabbitMq__Host=rabbitmq
      # - AnimalServiceUrl=http://animal-service:7001
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network

  search-service:
    build:
      context: .
      dockerfile: Services/SearchService/Dockerfile
    ports:
      - "7002:8080"
      - "7044:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbConnection=mongodb://mongodb_container:27017 # Corrected MongoDB connection string
      - RabbitMq__Host=rabbitmq
    depends_on:
      - mongodb_container
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
